version: '3.8'

services:
  meme-generator-optimized:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    ports:
      - "2233:2233"
    volumes:
      - ./data:/data
      - ./config:/app/config
      - ./static_cache:/app/static_cache  # 挂载静态缓存目录
    environment:
      - TZ=Asia/Shanghai
      - MEME_FAST_LOADING=true
      - LOAD_BUILTIN_MEMES=true
      - MEME_DIRS=[]
      - MEME_DISABLED_LIST=[]
      - GIF_MAX_SIZE=10.0
      - GIF_MAX_FRAMES=100
      - LOG_LEVEL=INFO
      # 翻译服务配置（根据需要取消注释）
      # - TRANSLATOR_TYPE=openai
      # - OPENAI_API_BASE=https://api.openai.com/v1
      # - OPENAI_API_KEY=your_openai_api_key
      # - OPENAI_MODEL=gpt-3.5-turbo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2233/memes/keys"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 可选：缓存预生成服务（用于定期更新缓存）
  cache-generator:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    volumes:
      - ./static_cache:/app/static_cache
    environment:
      - TZ=Asia/Shanghai
      - MEME_FAST_LOADING=false  # 禁用快速加载以便重新生成
    command: ["python", "static_generator.py", "--output-dir", "static_cache", "--force"]
    profiles: ["cache-update"]  # 只在需要时启动

volumes:
  data:
  config:
  static_cache: